### ISSUE TITLE
dart 2.0 and pub publish

### ISSUE THREAD

**Issue by ALMaclaine** [ahmetaa/dart-spell#1]
Will you consider upgrading this to dart 2 (looks like it's almost there) and publish to pub.dev?

If you are no longer interested in this project then I'd like permission to take it over.

Thanks

**Comment by ahmetaa** [comment]
I added you as a contributor. would that suffice?

**Comment by ALMaclaine** [comment]
Thank you, I think it should suffice, I'll let you know how upgrading and submission goes.

**Comment by ahmetaa** [comment]
@ALMaclaine Thanks, great that you took this over and make changes real fast. I hope this library worth the efforts you made.

**Comment by ALMaclaine** [comment]
Of course, my pleasure, I believe it will, if not to me then the community at large. I found it while looking for a spell checker for auto source generation like supported by source_gen and build. I'm looking to use it as a way to automate finding spelling mistakes in generated docs and such. There's no spell checker on pub so there's a good opportunity to build a foundational library I think.

**Comment by ahmetaa** [comment]
@ALMaclaine Excellent. I have some experience with spell checkers, language models and noisy text normalization (Especially for Turkish: https://github.com/ahmetaa/zemberek-nlp/tree/master/normalization). My day job domain has changed but If time permits, i try to give a hand. Thanks.

**Comment by ALMaclaine** [comment]
Oh that's really cool, I'll make sure to ask you anything I don't understand. Maybe we can get some of those missing features added.
